require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InvoiceRowsController do

  # This should return the minimal set of attributes required to create a valid
  # InvoiceRow. As you add validations to InvoiceRow, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "invoice_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InvoiceRowsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all invoice_rows as @invoice_rows" do
      invoice_row = InvoiceRow.create! valid_attributes
      get :index, {}, valid_session
      assigns(:invoice_rows).should eq([invoice_row])
    end
  end

  describe "GET show" do
    it "assigns the requested invoice_row as @invoice_row" do
      invoice_row = InvoiceRow.create! valid_attributes
      get :show, {:id => invoice_row.to_param}, valid_session
      assigns(:invoice_row).should eq(invoice_row)
    end
  end

  describe "GET new" do
    it "assigns a new invoice_row as @invoice_row" do
      get :new, {}, valid_session
      assigns(:invoice_row).should be_a_new(InvoiceRow)
    end
  end

  describe "GET edit" do
    it "assigns the requested invoice_row as @invoice_row" do
      invoice_row = InvoiceRow.create! valid_attributes
      get :edit, {:id => invoice_row.to_param}, valid_session
      assigns(:invoice_row).should eq(invoice_row)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InvoiceRow" do
        expect {
          post :create, {:invoice_row => valid_attributes}, valid_session
        }.to change(InvoiceRow, :count).by(1)
      end

      it "assigns a newly created invoice_row as @invoice_row" do
        post :create, {:invoice_row => valid_attributes}, valid_session
        assigns(:invoice_row).should be_a(InvoiceRow)
        assigns(:invoice_row).should be_persisted
      end

      it "redirects to the created invoice_row" do
        post :create, {:invoice_row => valid_attributes}, valid_session
        response.should redirect_to(InvoiceRow.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved invoice_row as @invoice_row" do
        # Trigger the behavior that occurs when invalid params are submitted
        InvoiceRow.any_instance.stub(:save).and_return(false)
        post :create, {:invoice_row => { "invoice_id" => "invalid value" }}, valid_session
        assigns(:invoice_row).should be_a_new(InvoiceRow)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InvoiceRow.any_instance.stub(:save).and_return(false)
        post :create, {:invoice_row => { "invoice_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invoice_row" do
        invoice_row = InvoiceRow.create! valid_attributes
        # Assuming there are no other invoice_rows in the database, this
        # specifies that the InvoiceRow created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InvoiceRow.any_instance.should_receive(:update).with({ "invoice_id" => "1" })
        put :update, {:id => invoice_row.to_param, :invoice_row => { "invoice_id" => "1" }}, valid_session
      end

      it "assigns the requested invoice_row as @invoice_row" do
        invoice_row = InvoiceRow.create! valid_attributes
        put :update, {:id => invoice_row.to_param, :invoice_row => valid_attributes}, valid_session
        assigns(:invoice_row).should eq(invoice_row)
      end

      it "redirects to the invoice_row" do
        invoice_row = InvoiceRow.create! valid_attributes
        put :update, {:id => invoice_row.to_param, :invoice_row => valid_attributes}, valid_session
        response.should redirect_to(invoice_row)
      end
    end

    describe "with invalid params" do
      it "assigns the invoice_row as @invoice_row" do
        invoice_row = InvoiceRow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InvoiceRow.any_instance.stub(:save).and_return(false)
        put :update, {:id => invoice_row.to_param, :invoice_row => { "invoice_id" => "invalid value" }}, valid_session
        assigns(:invoice_row).should eq(invoice_row)
      end

      it "re-renders the 'edit' template" do
        invoice_row = InvoiceRow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InvoiceRow.any_instance.stub(:save).and_return(false)
        put :update, {:id => invoice_row.to_param, :invoice_row => { "invoice_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invoice_row" do
      invoice_row = InvoiceRow.create! valid_attributes
      expect {
        delete :destroy, {:id => invoice_row.to_param}, valid_session
      }.to change(InvoiceRow, :count).by(-1)
    end

    it "redirects to the invoice_rows list" do
      invoice_row = InvoiceRow.create! valid_attributes
      delete :destroy, {:id => invoice_row.to_param}, valid_session
      response.should redirect_to(invoice_rows_url)
    end
  end

end
